// android/build.gradle — 根项目构建文件（Groovy DSL，新 DSL 兼容）
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean") {
    delete rootProject.buildDir
}
